name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: cargofran  # Ensures the repo is cloned into this subdirectory

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify Node.js version if needed
          cache: 'npm'
          cache-dependency-path: cargofran/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: cargofran

      - name: Build project
        run: npm run build
        working-directory: cargofran

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: cargofran/dist  # Ensure correct path to built files

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
